# /intelligent-query-retrieval-system/app/api_models.py

from pydantic import BaseModel, Field
from typing import List

class QueryRequest(BaseModel):
    """
    Request model for query processing.
    Expects a document URL and a list of questions.
    """
    documents: str = Field(..., description="URL to a PDF, DOCX, or EML document.")
    questions: List[str] = Field(..., description="List of questions to ask about the document.")

class QueryResponse(BaseModel):
    """
    Response model for processed answers.
    Returns a list of generated answers corresponding to the input questions.
    """
    answers: List[str] = Field(..., description="List of answers generated by the LLM.")